List<String> mamarasulovflutterUrl = [
  "5s-ZbHNczP4",
  "izQOIcHWins",
  "5ws1XslzuIs",
  "CvyVtbBQ7HQ",
  "VO1GYblR7bM",
  "Ene_GrtayZQ",
  "PQkYqU6WZ_A",
  "1wJeQ0yfrII",
  "d5lt8LcNsFc",
  "9MrSYLVCeYQ",
  "w1-PotK1TVc",
  "Spn8ud5obJ0",
  "3hIod69i6So",
  "ZiSfhdc7FW0",
  "Aw5O7mFwIbE",
  "GnhfsFjWC30",
  "IzPiPnWMd3o",
  "yIpSvpMAFQg",
  "Y3MD0AhKzwU"
];
List<String> mamarasulovflutterTitle = [
  "Kirish",
  "Widgets beginner,Text fonts",
  "Navigation",
  "Drawer,ListView",
  "PageView,TabBarView",
  "Decorations",
  "SliverAppBar",
  "Responsive,Adaptive",
  "Animations",
  "URL launcher,",
  "Navigation Rail",
  "Restoran menu",
  "Restoran menu 2-qism",
  "Localization",
  "Flutter web",
  "Publishing to host",
  "DetailsPage",
  "Favorites list",
  "Play marketga yuklash"
];
