List<String> ziyatovPythonUrl = [
  "_f8cpjAz0sw",
  "fj_GLU344bQ&t=2s",
  "Q3H1OUj_XU8",
  "-haxzF1rzZ0",
  "slMBSFsORow",
  "o5XIOTLBPIU",
  "ixc2mq0FKHA",
  "RhgjRtIEFnI",
  "DAQClN-s6y4",
  "5ZAsEq94TA0",
  "_cvnzZN5eic",
  "S5zqzqZSJgk",
  "tykfZMFi7Pk",
  "MYQi17lZwwA",
  "4odkjB1BEaY",
];

List<String> ziyatovPythonTitle = [
  "Imkoniyatlari",
  "Kirish",
  "O'zgaruchilar",
  "Ma'lumot turlari",
  "Operatorlar",
  "String",
  "Chiziqli dastur",
  "Shartlar, if, else",
  "If, murakkab shartlar",
  "For aylanma",
  "While aylanma",
  "Aylanma, turtle",
  "List, Pygal charts",
  "Dict, Json",
  "Funksiya",
];
